
server:
  port: 0

spring:
  application:
    name: ordering-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  expiration: 30
  secretKey: MXfAuvUHe7vyOo6rfHPMZga4b7YgvokM/B9ytSRaAYsXii76YlbTPPvE6KtgHqUvhfSU528DjR4H1xUNGuIzQg==

  expirationRt: 14400
  secretKeyRt: yajVyBouoQWnRXj1g7xxSTXMamcw3p2hEEbhe3cFzxuHXsg4IXVe+qN9baNmuxd2Fo+YbB6VeBSI0AIz2Frw9w==

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
