server:
  port: 8888

spring:
#  profiles:
#    active: native
  application:
    name: config-service
  # ??? ???? ??
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///Users/stephen/Desktop/develop/git-local-repo
        git:
          # 호스트 키는 SSH 프로토콜을 통해 Git 저장소에 접근할 때 Git 서버의 신뢰성을 검증하기 위한
          # 호스트 키를 제공해야 합니다.
          uri: git@github.com:bildno/cloude-config-settings.git
          default-label: main
          host-key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
          host-key-algorithm: "ssh-rsa"
          private-key: |
            ${GIT_PRIVATE_KEY}


